# Generated by Django 2.2.9 on 2020-01-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0001_initial'),
        ('groups_app', '0002_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers_app.Teacher'),
        ),
    ]
