# Generated by Django 2.2.9 on 2020-01-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
        ('groups_app', '0003_group_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='starosta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students_app.Student'),
        ),
    ]
